--- #YAML:1.0
name:                File-Path
version:             2.05
abstract:            Create or remove directory trees
license:             perl
author:              
    - David Landgren
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Cwd:                           0
    File::Basename:                0
    File::Spec:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
