--- #YAML:1.0
name:                File-Path
version:             1.99_01
abstract:            create or remove directory trees
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32_01
distribution_type:   module
requires:     
    File::Basename:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Landgren
